"""add_webhook_logs_table

Revision ID: 91efce206053
Revises: 7bdc9f61f419
Create Date: 2026-03-17 22:58:29.010382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91efce206053'
down_revision: Union[str, None] = '7bdc9f61f419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chats', 'is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'sources',
               existing_type=postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
               type_=sa.ARRAY(sa.JSON()),
               existing_nullable=True)
    op.alter_column('subscription_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subscription_history', 'payment_reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscription_history', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscription_history', 'payment_status',
               existing_type=postgresql.ENUM('successful', 'failed', 'pending', 'refunded', name='paymentstatus'),
               nullable=True)
    op.alter_column('subscription_history', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscription_history', 'plan_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscription_history', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscription_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscription_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subscription_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subscription_history', 'duration_months',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscription_history', 'plan_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscription_history', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subscription_history', 'payment_status',
               existing_type=postgresql.ENUM('successful', 'failed', 'pending', 'refunded', name='paymentstatus'),
               nullable=False)
    op.alter_column('subscription_history', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscription_history', 'payment_reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscription_history', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'sources',
               existing_type=sa.ARRAY(sa.JSON()),
               type_=postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
               existing_nullable=True)
    op.alter_column('chats', 'is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
